"""
crowd_detector.py  —  Temple Crowd Detection & Heatmap
=======================================================
Reads calibration from  calibration.json  (generated by calibration_tool.py),
runs YOLOv8 on the video, transforms person foot-points to map coordinates,
and emits them to the Node.js server via Socket.IO.
"""

import cv2
import numpy as np
import socketio
import json
import os
from ultralytics import YOLO

# ==================== CONFIG ====================
VIDEO_PATH       = r'D:\PravaahProject(finalai)\pravaah project_till heatmap - Copy\pravaah project_till heatmap\pravaah project\backend\public\assets\crowd1.mp4'
CALIBRATION_FILE = 'calibration.json'

# ==================== LOAD CALIBRATION ====================
# FIX: load from the JSON saved by calibration_tool.py instead of
#      hardcoding points. MAP_WIDTH / MAP_HEIGHT are also stored so
#      the frontend can scale correctly.

if not os.path.exists(CALIBRATION_FILE):
    print(f"❌ {CALIBRATION_FILE} not found!")
    print("   Run  python calibration_tool.py  first, then retry.")
    exit(1)

with open(CALIBRATION_FILE) as f:
    cal = json.load(f)

VIDEO_POINTS = np.float32(cal['video_points'])
MAP_POINTS   = np.float32(cal['map_points'])
MAP_WIDTH    = cal['map_width']
MAP_HEIGHT   = cal['map_height']

print(f"✅ Calibration loaded from {CALIBRATION_FILE}")
print(f"   Map size : {MAP_WIDTH} × {MAP_HEIGHT}")
print(f"   Video pts: {VIDEO_POINTS.tolist()}")
print(f"   Map pts  : {MAP_POINTS.tolist()}")

# ==================== SOCKET ====================
sio = socketio.Client()

@sio.event
def connect():
    print("✅ Connected to Node server")

@sio.event
def disconnect():
    print("❌ Disconnected from Node server")

sio.connect('http://localhost:3000')

# ==================== LOAD MODEL ====================
model = YOLO("yolov8n.pt")
print("✅ YOLO model loaded")

# ==================== HOMOGRAPHY ====================
H, status = cv2.findHomography(VIDEO_POINTS, MAP_POINTS)
if H is None:
    print("❌ Could not compute homography — are your calibration points correct?")
    exit(1)
print(f"✅ Homography computed (inliers: {status.sum()}/4)")

# ==================== VIDEO ====================
cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    print("❌ Cannot open video:", VIDEO_PATH)
    exit(1)

print("▶ Processing video…  (Esc to quit)")

# ==================== MAIN LOOP ====================
while True:
    ret, frame = cap.read()
    if not ret:
        cap.set(cv2.CAP_PROP_POS_FRAMES, 0)   # loop video
        continue

    results = model(frame, verbose=False)

    foot_points = []   # bottom-center of each detected person (in video coords)

    for r in results:
        for box in r.boxes:
            if int(box.cls[0]) != 0:   # class 0 = person
                continue
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cx = int((x1 + x2) / 2)
            cy = int(y2)               # foot point
            foot_points.append([cx, cy])
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.circle(frame,  (cx, cy),   5,         (0, 0, 255), -1)

    # ==================== PERSPECTIVE TRANSFORM ====================
    # FIX: transformed points land in the natural pixel space of the map
    #      image (MAP_WIDTH × MAP_HEIGHT). The frontend scales them to the
    #      display container using naturalWidth / naturalHeight.
    transformed_points = []

    if foot_points:
        pts = np.array(foot_points, dtype=np.float32).reshape(-1, 1, 2)
        warped = cv2.perspectiveTransform(pts, H)
        for pt in warped:
            x, y = float(pt[0][0]), float(pt[0][1])
            transformed_points.append({"x": x, "y": y, "value": 1})

    # ==================== ZONES ====================
    # Zone thresholds expressed as fractions of MAP_WIDTH so they work
    # regardless of the actual image resolution.
    zones = {"entrance": 0, "queue": 0, "sanctum": 0, "exit": 0}

    for pt in transformed_points:
        x = pt["x"]
        if   x < MAP_WIDTH * 0.25:  zones["entrance"] += 1
        elif x < MAP_WIDTH * 0.50:  zones["queue"]    += 1
        elif x < MAP_WIDTH * 0.75:  zones["sanctum"]  += 1
        else:                        zones["exit"]     += 1

    # ==================== ALERTS ====================
    alerts = []
    if zones["queue"]   > 10: alerts.append("🚨 Queue overcrowded")
    if zones["sanctum"] > 5:  alerts.append("❌ Sanctum full")

    # ==================== WAITING TIME ====================
    flow_rate    = 2   # people / second
    waiting_time = zones["queue"] / flow_rate if flow_rate > 0 else 0

    # ==================== EMIT TO SERVER ====================
    sio.emit("crowd_update", {
        "points":       transformed_points,   # [{x, y, value}, …]
        "totalCount":   len(transformed_points),
        "zones":        zones,
        "alerts":       alerts,
        "waiting_time": waiting_time,
        # Send map dimensions so the frontend can scale correctly
        "map_width":    MAP_WIDTH,
        "map_height":   MAP_HEIGHT,
    })

    # ==================== DISPLAY ====================
    cv2.putText(frame, f"People: {len(foot_points)}", (20, 40),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow("Crowd Detection", frame)

    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()
sio.disconnect()
